FROM alpine:latest
WORKDIR /app
RUN apk add nodejs npm
RUN npm install -g yarn
COPY package.json .
COPY yarn.lock .
COPY .yarnrc.yml .
COPY .yarn ./.yarn/
COPY packages/mongo-proxy/package.json ./packages/mongo-proxy/package.json
RUN yarn workspaces focus @kanban/mongo-proxy
CMD echo "y\n" | yarn workspace @kanban/mongo-proxy dev