version: "3.9"
services:
  kanban-postgres:
    container_name: kanban-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    networks:
      - kanban-network
networks:
  kanban-network:
    driver: bridge
