version: "3.9"
services:
  kanban-mongo:
    container_name: kanban-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - kanban-network
  kanban-mongo-proxy:
    container_name: kanban-mongo-proxy
    restart: always
    tty: true
    build:
      context: .
      dockerfile: docker/mongo-proxy/Dockerfile.dev
    ports:
      - "7000:7000"
    volumes:
      - ./packages/mongo-proxy:/app/packages/mongo-proxy
    networks:
      - kanban-network
networks:
  kanban-network:
    driver: bridge
