FROM alpine:latest
WORKDIR /app
RUN apk add nodejs npm
RUN npm install -g yarn
COPY package.json .
COPY yarn.lock .
COPY .yarnrc.yml .
COPY .yarn ./.yarn/
COPY packages/fe/package.json ./packages/fe/package.json
RUN yarn workspaces focus @kanban/fe
CMD yarn workspace @kanban/fe dev --host