name = "main"
main = "src/index.ts"
compatibility_date = "2022-11-22"
node_compat = true

[dev]
port = 8001

[env.development.vars]
ENVIRONMENT = "Development"
DATABASE_URL = "postgresql://pguser:pgpassword@localhost:5432/kanban"
FRONTEND_URL = "http://localhost:5173"
JWT_SECRET = "secret"

[env.testing.vars]
ENVIRONMENT = "Testing"
DATABASE_URL = "postgresql://pguser:pgpassword@localhost:5432/kanban"
FRONTEND_URL = "http://localhost:5173"
JWT_SECRET = "secret"