name = "main"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8001

[env.development.vars]
ENVIRONMENT = "Development"
DATABASE_URL = "postgresql://pguser:pgpassword@localhost:5432/kanban"
FRONTEND_URL = "http://localhost:5173"
JWT_SECRET = "secret"

[env.testing.vars]
ENVIRONMENT = "Testing"
DATABASE_URL = "postgresql://pguser:pgpassword@localhost:5432/kanban"
FRONTEND_URL = "http://localhost:5173"
JWT_SECRET = "secret"
