name = "main"
main = "dist/index.js"
compatibility_date = "2022-11-22"
node_compat = true

[build]
command = "yarn && yarn build"

[dev]
port = 8001

[env.development.vars]
ENVIRONMENT = "Development"
DATABASE_URL = "postgresql://pguser:pgpassword@localhost:5432/kanban"
JWT_SECRET = "secret"

[env.testing.vars]
ENVIRONMENT = "Testing"
DATABASE_URL = "postgresql://pguser:pgpassword@localhost:5432/kanban"
JWT_SECRET = "secret"