name: Publish reset-db cron trigger to Cloudflare Workers
on:
  push:
    branches: [prod]
    paths:
      - "packages/backend/workers/reset-db/**"

jobs:
  publish-reset-db:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Workers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install wrangler-cli
        run: npm install -g wrangler
      - name: Install dependencies
        run: yarn workspaces focus @kanban/reset-db-worker
      - name: Deploy
        run: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} yarn workspace @kanban/reset-db-worker deploy
