name: Publish front-end to Cloudflare Pages
on:
  push:
    branches: [prod]
    paths:
      - "packages/frontend/**"
  workflow_dispatch:

jobs:
  publish-fe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Copy production env
        run: cp packages/frontend/.env.prod packages/frontend/.env
      - name: Build
        run: |
          yarn && \
          yarn workspace @kanban/main-worker prisma:generate && \
          yarn workspace @kanban/main-worker build && \
          yarn workspace @kanban/frontend build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy packages/frontend/dist --project-name=kanban --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
