name: Publish front-end to Cloudflare Pages
on:
  push:
    branches: [prod]
    paths:
      - "packages/frontend/**"

jobs:
  publish-fe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: test
        run: node --version
      - name: Build
        run: yarn workspaces focus @kanban/frontend && yarn workspace @kanban/frontend build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kanban
          directory: packages/frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
