name: Publish back-end to Cloudflare Workers
on:
  push:
    branches: [prod]
    paths:
      - "packages/backend/workers/main/**"
      - "packages/backend/libs/base/**"

jobs:
  publish-be:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Workers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install wrangler-cli
        run: npm install -g wrangler
      # - name: Launch test container
      #   run: yarn && yarn docker:start:test
      # - name: Wait 10 seconds
      #   run: sleep 10
      - name: Build
        run: yarn workspaces focus @kanban/main-worker && yarn workspace @kanban/main-worker build 
      # - name: Run tests
      #   run: yarn workspace @kanban/be test
      - name: Apply prisma migration
        run: DATABASE_URL=${{ secrets.DATABASE_URL }} yarn workspace @kanban/main-worker prisma:migrate:deploy
      - name: Deploy
        run: cd packages/backend/workers/main/dist && CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} wrangler deploy index.js --compatibility-date 2022-11-22 --node-compat --name main
